[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Joao Martins <mdj@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
